apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: jmeter-${JOB_NAME}
  labels:
    app: jmeter-${JOB_NAME}
    environment: staging
    flavour: pipeline
spec:
  restartPolicy: Never
  volumes:
    - name: jmeter-dir
      hostPath:
        path: /mnt/k8s/jmeter
  containers:
    - name: jmeter
      image: taskiy/jmeter:5.3
      volumeMounts:
        - name: jmeter-dir
          mountPath: "/mnt/jmeter"
      args: [
        "-n", 
        "-t", "/mnt/jmeter/scripts/$(JMETER_SCRIPT).jmx"
      ]
  nodeSelector:
    kubernetes.io/hostname: stg-w3